name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull the latest image
        run: docker pull Shakshi25/booksearch-app:latest

      - name: Stop old container
        run: docker stop booksearch-app || true && docker rm booksearch-app || true

      - name: Run New Container
        run: docker run -d -p 3000:3000 --name booksearch-app Shakshi25/booksearch-app:latest
